package com.ibm.issue.dao;

import com.ibm.issue.pojo.Identity;
import com.ibm.issue.pojo.IdentityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    long countByExample(IdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    int deleteByExample(IdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    int insert(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    int insertSelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    List<Identity> selectByExample(IdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    Identity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Identity record, @Param("example") IdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Identity record, @Param("example") IdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Identity record);
}