package com.ibm.issue.dao;

import com.ibm.issue.pojo.Lssuestate;
import com.ibm.issue.pojo.LssuestateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LssuestateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    long countByExample(LssuestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    int deleteByExample(LssuestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    int insert(Lssuestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    int insertSelective(Lssuestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    List<Lssuestate> selectByExample(LssuestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    Lssuestate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Lssuestate record, @Param("example") LssuestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Lssuestate record, @Param("example") LssuestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Lssuestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lssuestate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Lssuestate record);
}